//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_TicaretOtomasyonu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLADMINLER> TBLADMINLER { get; set; }
        public virtual DbSet<TBLADRESLER> TBLADRESLER { get; set; }
        public virtual DbSet<TBLBILGILER> TBLBILGILER { get; set; }
        public virtual DbSet<TBLKAMPANYALAR> TBLKAMPANYALAR { get; set; }
        public virtual DbSet<TBLKATEGORILER> TBLKATEGORILER { get; set; }
        public virtual DbSet<TBLKULLANICILAR> TBLKULLANICILAR { get; set; }
        public virtual DbSet<TBLMAGAZA> TBLMAGAZA { get; set; }
        public virtual DbSet<TBLSIPARIS> TBLSIPARIS { get; set; }
        public virtual DbSet<TBLSIPARISDETAY> TBLSIPARISDETAY { get; set; }
        public virtual DbSet<TBLURUNLER> TBLURUNLER { get; set; }
        public virtual DbSet<TBLYORUMLAR> TBLYORUMLAR { get; set; }
    }
}
