//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_TicaretOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADRESLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLADRESLER()
        {
            this.TBLSIPARIS = new HashSet<TBLSIPARIS>();
        }
    
        public int ID { get; set; }
        public string AdresAdi { get; set; }
        public string AdresAciklama { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> EvNo { get; set; }
        public Nullable<int> ApartmanNo { get; set; }
        public string Sehir { get; set; }
        public string Ulke { get; set; }
    
        public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPARIS> TBLSIPARIS { get; set; }
    }
}
