//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_TicaretOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICILAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKULLANICILAR()
        {
            this.TBLADRESLER = new HashSet<TBLADRESLER>();
            this.TBLSIPARIS = new HashSet<TBLSIPARIS>();
            this.TBLYORUMLAR = new HashSet<TBLYORUMLAR>();
        }
    
        public int ID { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciMail { get; set; }
        public string KullaniciSifre { get; set; }
        public string KullaniciRol { get; set; }
        public Nullable<System.DateTime> KullaniciKatilimTarihi { get; set; }
        public string KullaniciTel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLADRESLER> TBLADRESLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSIPARIS> TBLSIPARIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLYORUMLAR> TBLYORUMLAR { get; set; }
    }
}
